name: Telegram Quiz Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: telegram-quiz-bot:latest

    - name: Run Docker container
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        TELEGRAM_CHANNEL_USERNAME: ${{ secrets.DEFAULT_CHANNEL }}
        MONGO_CONNECTION_STRING: ${{ secrets.MONGO_URI }}
        TEMPLATE_URL: ${{ secrets.TEMPLATE_URL }}
      run: |
        docker run --rm \
          -e TELEGRAM_BOT_TOKEN \
          -e TELEGRAM_CHANNEL_USERNAME \
          -e MONGO_CONNECTION_STRING \
          -e TEMPLATE_URL \
          telegram-quiz-bot:latest
