name: Telegram Quiz Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install LibreOffice
      run: sudo apt-get update && sudo apt-get install -y libreoffice
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run the script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        TELEGRAM_CHANNEL_USERNAME: ${{ secrets.DEFAULT_CHANNEL }}
        MONGO_CONNECTION_STRING: ${{ secrets.MONGO_URI }}
        TEMPLATE_URL: ${{ secrets.TEMPLATE_URL }}
      run: |
        python main.py
